services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    image: linkliberate
    ports:
      - "8080:8080"
    command: ["pdm", "run", "start"]
    volumes:
      - "./data/liberate.db:/project/liberate.db"